name: Apply Flyway migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Flyway
        run: |
          curl -L -o flyway-commandline.tar.gz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz"
          tar -xzf flyway-commandline.tar.gz
          sudo ln -s `pwd`/flyway-11.1.0/flyway /usr/local/bin/flyway

      - name: Wait for Postgres
        run: until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Run Flyway migrations
        env:
          FLYWAY_URL: "jdbc:postgresql://localhost:5432/testdb"
          FLYWAY_USER: testuser
          FLYWAY_PASSWORD: testpassword
        run: flyway migrate -locations=filesystem:sql/migrations
